version: "3.8"


services:
  db:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.11
    env_file: .env
    restart: unless-stopped
  receiver: &python-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: python receiver.py
  web:
    <<: *python-service
    ports:
      - "${DOCKER_EXPOSE_PORT:-8000}:${DJANGO_PORT:-8000}"
    command: gunicorn --bind :${DJANGO_PORT:-8000} --workers 8 ducatus_exchange.wsgi:application
  lottery_checker:
    <<: *python-service
    command: python lottery_checker.py
  rates_checker:
    <<: *python-service
    command: python rates_checker.py
  stats_checker_ducx:
    <<: *python-service
    command: python stats_checker.py DUCX
  stats_checker_duc:
    <<: *python-service
    command: python stats_checker.py DUC
  celery:
    <<: *python-service
    command: celery -A celery_config worker -B --loglevel=info
  bot:
    <<: *python-service
    command: python start_bot_polling.py
