version: "3.8"


services:
  db:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    command: postgres -c 'max_connections=1000'
    volumes:
      - ./multiple_db/:/docker-entrypoint-initdb.d
      - ./.docker/postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.11
    env_file: .env
    restart: unless-stopped
    logging:
      # limit logs retained on host to 2GB
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "4"
  lottery_checker: &python-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: python lottery_checker.py
    logging:
      # limit logs retained on host to 2GB
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "4"
  web:
    <<: *python-service
    ports:
      - "${DOCKER_EXPOSE_PORT:-8000}:${DJANGO_PORT:-8000}"
    command: gunicorn --bind :${DJANGO_PORT:-8000} --workers 8 ducatus_exchange.wsgi:application
    logging:
      # limit logs retained on host to 2GB
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "4"
  rates_checker:
    <<: *python-service
    command: python rates_checker.py
  stats_checker_ducx:
    <<: *python-service
    command: python stats_checker.py --network DUCX
  stats_checker_duc:
    <<: *python-service
    command: python stats_checker.py --network DUC
    # stats_checker_balances:
    # st<<: *python-service
    # stcommand: python stats_checker.py --balances
  celery:
    <<: *python-service
    command: celery -A celery_config worker -B --loglevel=info
  bot:
    <<: *python-service
    command: python start_bot_polling.py
  scanner:
    image: rocknblock/scanner:latest
    depends_on:
      - db
      - web
    env_file:
      - .env
    volumes:
      - ./scanner_config.yaml:/app/scanner_config.yaml
      - ./.docker/scanner/migrations:/app/migrations
    tty: true
    logging:
      # limit logs retained on host to 2GB
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "4"
