FROM python:3.8-alpine


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /www
WORKDIR /www
COPY ./ /www/ducatus_exchange_backend
COPY ./requirements.txt /requirements.txt
RUN python3 -m venv /opt/venv
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev
#RUN apk add --update --no-cache postgresql-client
#RUN apk add --update --no-cache --virtual .tmp-build-deps \
#      gcc libc-dev linux-headers postgresql-dev musl-dev
RUN apk update && apk add libpq

#RUN pip install --upgrade setuptools
#RUN /opt/venv/bin/python3 -m pip install --upgrade pip
RUN . /opt/venv/bin/activate && pip install --upgrade -r /requirements.txt

#RUN apk del .tmp-build-deps


